<?php

namespace App\Services\Shemas\Leads;

/**
 * @OA\Schema(
 *     title="GetLead",
 *     description="GetLead Shemas",
 *     @OA\Xml(
 *         name="GetLead"
 *     )
 * )
 * @OA\Property(
 *     property="id",
 *     title="Id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="lead_status_id",
 *     title="lead_status_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="manager_id",
 *     title="manager_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="organization_id",
 *     title="organization_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="terms_payment_id",
 *     title="terms_payment_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="form_payment_id",
 *     title="form_payment_id",
 *     example=1,
 *     type="int"
 * )
 *  @OA\Property(
 *     property="partner_type_id",
 *     title="partner_type_id",
 *     example=1,
 *     type="int"
 * )
 *  @OA\Property(
 *     property="sex_id",
 *     title="sex_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="price_id",
 *     title="price_id",
 *     example=1,
 *     type="int"
 * )
 * @OA\Property(
 *     property="title",
 *     title="title",
 *     example="title",
 *     type="string"
 * )
 * @OA\Property(
 *     property="title_middle_name",
 *     title="title_middle_name",
 *     example="title",
 *     type="string"
 * )
 * @OA\Property(
 *     property="title_last_name",
 *     title="title_last_name",
 *     example="title",
 *     type="string"
 * )
 * @OA\Property(
 *     property="title_first_name",
 *     title="title_first_name",
 *     example="title",
 *     type="string"
 * )
 * @OA\Property(
 *     property="manager",
 *     title="manager",
 *     example="manager manager manager",
 *     type="string"
 * )
 * @OA\Property(
 *     property="loyalty",
 *     title="loyalty",
 *     example=10,
 *     type="int"
 * )
 * @OA\Property(
 *     property="discount",
 *     title="discount",
 *     example=10,
 *     type="int"
 * )
 * @OA\Property(
 *     property="partner_inn",
 *     title="partner_inn",
 *     example=155654654,
 *     type="int"
 * )
 * @OA\Property(
 *     property="partner_edrpou",
 *     title="partner_edrpou",
 *     example=1556,
 *     type="int"
 * )
 * @OA\Property(
 *     property="created_at",
 *     title="created at",
 *     example="2020-12-16",
 *     type="date"
 * )
 * @OA\Property(
 *     property="sum_price",
 *     title="sum price",
 *     example=100,
 *     type="int"
 * )
 * @OA\Property(
 *     property="sum_balance",
 *     title="sum balance",
 *     example=50,
 *     type="int"
 * )
 * @OA\Property(
 *     property="sum_product_balance",
 *     title="sum_product_balancee",
 *     example=50,
 *     type="int"
 * )
 * @OA\Property(
 *     property="sum_service_balance",
 *     title="sum_service_balance",
 *     example=50,
 *     type="int"
 * )
 * @OA\Property(
 *     property="sum_product_price",
 *     title="sum_product_price",
 *     example=50,
 *     type="int"
 * )
 *  @OA\Property(
 *     property="sum_service_price",
 *     title="sum_service_price",
 *     example=50,
 *     type="int"
 * )
 * @OA\Property(
 *     property="sum_discount_price",
 *     title="sum_discount_price",
 *     example=50,
 *     type="int"
 * )
 * @OA\Property(
 *     property="comments",
 *     title="Сomments",
 *     example="comments",
 *     type="string"
 * )
 * @OA\Property(
 *     property="delivery",
 *     title="Delivery",
 *       ref="#/components/schemas/LeadDelivery"
 * )
 * @OA\Property(
 *     property="categories",
 *     title="categories",
 *       ref="#/components/schemas/Categories"
 * )
 * @OA\Property(
 *     property="employee",
 *     title="employee",
 *       ref="#/components/schemas/DirectoriesDetail"
 * )
 * @OA\Property(
 *     property="lead_status",
 *     title="employee",
 *       ref="#/components/schemas/DirectoriesDetail"
 * )
 * @OA\Property(
 *     property="organization",
 *     title="employee",
 *       ref="#/components/schemas/DirectoriesDetail"
 * )
 * @OA\Property(
 *                 property="nomenclatures",
 *                 title="Get nomenclatures",
 *                 @OA\Property(
 *                    property="headers",
 *                    title="Get Table Data Header",
 *                    type="array",
 *                    collectionFormat="multi",
 *                    @OA\Items(
 *                         ref="#/components/schemas/DirectoriesHeader"
 *                    )
 *                  ),
 *                  @OA\Property(
 *                    property="body",
 *                    title="Get Table Data Body",
 *                    type="array",
 *                    collectionFormat="multi",
 *                    @OA\Items(
 *                         ref="#/components/schemas/Directories"
 *                    )
 *                  ),
 *                )
 */
class GetLead
{

}
