FROM nginx:latest

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
       libjpeg62-turbo-dev \
       libpng-dev \
       git \
       jpegoptim optipng pngquant gifsicle \
       vim \
       nano \
       curl \
       zip \
       unzip \
       mc \